<a href="https://www.kaggle.com/code/rkmaurya93/market-prediction?scriptVersionId=262725222" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/kaggle/input/hull-tactical-market-prediction/train.csv")

In [3]:
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301

In [4]:
df.columns

Index(['date_id', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'E1',
       'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19',
       'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'I1', 'I2', 'I3',
       'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1', 'M10', 'M11', 'M12', 'M13',
       'M14', 'M15', 'M16', 'M17', 'M18', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7',
       'M8', 'M9', 'P1', 'P10', 'P11', 'P12', 'P13', 'P2', 'P3', 'P4', 'P5',
       'P6', 'P7', 'P8', 'P9', 'S1', 'S10', 'S11', 'S12', 'S2', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2',
       'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'forward_returns',
       'risk_free_rate', 'market_forward_excess_returns'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8990 entries, 0 to 8989
Data columns (total 98 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        8990 non-null   int64
 1   D1                             8990 non-null   int64
 2   D2                             8990 non-null   int64
 3   D3                             8990 non-null   int64
 4   D4                             8990 non-null   int64
 5   D5                             8990 non-null   int64
 6   D6                             8990 non-null   int64
 7   D7                             8990 non-null   int64
 8   D8                             8990 non-null   int64
 9   D9                             8990 non-null   int64
 10  E1                             7206 non-null   float64
 11  E10                            7984 non-null   float64
 12  E11                            7984 non-null   float64
 13  E12                            7984 non-null   float64
 14  E13                            7984 non-null   float64
 15  E14                            7984 non-null   float64
 16  E15                            7984 non-null   float64
 17  E16                            7984 non-null   float64
 18  E17                            7984 non-null   float64
 19  E18                            7984 non-null   float64
 20  E19                            7984 non-null   float64
 21  E2                             7984 non-null   float64
 22  E20                            7374 non-null   float64
 23  E3                             7984 non-null   float64
 24  E4                             7984 non-null   float64
 25  E5                             7984 non-null   float64
 26  E6                             7984 non-null   float64
 27  E7                             2021 non-null   float64
 28  E8                             7984 non-null   float64
 29  E9                             7984 non-null   float64
 30  I1                             7984 non-null   float64
 31  I2                             7984 non-null   float64
 32  I3                             7984 non-null   float64
 33  I4                             7984 non-null   float64
 34  I5                             7984 non-null   float64
 35  I6                             7984 non-null   float64
 36  I7                             7984 non-null   float64
 37  I8                             7984 non-null   float64
 38  I9                             7984 non-null   float64
 39  M1                             3443 non-null   float64
 40  M10                            7984 non-null   float64
 41  M11                            7984 non-null   float64
 42  M12                            7984 non-null   float64
 43  M13                            3450 non-null   float64
 44  M14                            3450 non-null   float64
 45  M15                            7984 non-null   float64
 46  M16                            7984 non-null   float64
 47  M17                            7984 non-null   float64
 48  M18                            7984 non-null   float64
 49  M2                             5773 non-null   float64
 50  M3                             6972 non-null   float64
 51  M4                             7984 non-null   float64
 52  M5                             5707 non-null   float64
 53  M6                             3947 non-null   float64
 54  M7                             7984 non-null   float64
 55  M8                             7984 non-null   float64
 56  M9                             7984 non-null   float64
 57  P1                             7984 non-null   float64
 58  P10                            7984 non-null   float64
 59  P11                            7984 non-null   float64
 60  P12                            7984 non-null   float64
 61  P13                            7984 non-null   float64
 62  P2                             7984 non-null   float64
 63  P3                             7984 non-null   float64
 64  P4                             7984 non-null   float64
 65  P5                             7416 non-null   float64
 66  P6                             7352 non-null   float64
 67  P7                             7374 non-null   float64
 68  P8                             7984 non-null   float64
 69  P9                             7984 non-null   float64
 70  S1                             7984 non-null   float64
 71  S10                            7984 non-null   float64
 72  S11                            7984 non-null   float64
 73  S12                            5453 non-null   float64
 74  S2                             7984 non-null   float64
 75  S3                             3257 non-null   float64
 76  S4                             7984 non-null   float64
 77  S5                             7479 non-null   float64
 78  S6                             7984 non-null   float64
 79  S7                             7984 non-null   float64
 80  S8                             5981 non-null   float64
 81  S9                             7984 non-null   float64
 82  V1                             7984 non-null   float64
 83  V10                            2941 non-null   float64
 84  V11                            7984 non-null   float64
 85  V12                            7984 non-null   float64
 86  V13                            7479 non-null   float64
 87  V2                             7984 non-null   float64
 88  V3                             7984 non-null   float64
 89  V4                             7984 non-null   float64
 90  V5                             7478 non-null   float64
 91  V6                             7984 non-null   float64
 92  V7                             7479 non-null   float64
 93  V8                             7984 non-null   float64
 94  V9                             4451 non-null   float64
 95  forward_returns                8990 non-null   float64
 96  risk_free_rate                 8990 non-null   float64
 97  market_forward_excess_returns  8990 non-null   float64
dtypes: float64(88), int64(10)
memory usage: 6.7 MB

In [6]:
df.describe()

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
count,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,8990.000000,...,7984.000000,7984.000000,7478.000000,7984.000000,7479.000000,7984.000000,4451.000000,8990.000000,8990.000000,8990.000000
mean,4494.500000,0.031591,0.031591,0.047831,0.575195,0.190656,-0.238042,0.045717,0.142825,0.143159,...,0.489553,0.506930,0.372494,0.287179,0.148270,0.303908,0.129227,0.000469,0.000107,0.000051
std,2595.333794,0.174917,0.174917,0.213420,0.494341,0.392840,0.425909,0.208883,0.349914,0.350254,...,0.306230,0.306554,1.153280,0.312238,1.326879,0.351109,1.277273,0.010551,0.000088,0.010568
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000661,0.000661,-2.723527,0.000661,-2.027551,0.000661,-1.497420,-0.039754,-0.000004,-0.040582
25%,2247.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.207011,0.236111,-0.472864,0.000661,-0.797168,0.000661,-0.738242,-0.004324,0.000008,-0.004759
50%,4494.500000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.492394,0.519180,0.275162,0.180225,-0.097670,0.101025,-0.170825,0.000659,0.000095,0.000252
75%,6741.750000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.760582,0.772487,1.125069,0.515873,0.795763,0.590030,0.685907,0.005900,0.000193,0.005479
max,8989.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,6.809912,1.000000,12.678264,1.000000,12.997536,0.040661,0.000317,0.040551

In [7]:
df.isnull().sum()

date_id                             0
D1                                  0
D2                                  0
D3                                  0
D4                                  0
                                 ...
V8                               1006
V9                               4539
forward_returns                     0
risk_free_rate                      0
market_forward_excess_returns       0
Length: 98, dtype: int64

In [8]:
feature_groups = {
    'D': [col for col in df.columns if col.startswith('D')],
    'E': [col for col in df.columns if col.startswith('E')],
    'I': [col for col in df.columns if col.startswith('I')],
    'M': [col for col in df.columns if col.startswith('M')],
    'P': [col for col in df.columns if col.startswith('P')],
    'S': [col for col in df.columns if col.startswith('S')],
    'V': [col for col in df.columns if col.startswith('V')],
}

In [9]:
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301

In [10]:
for group, cols in feature_groups.items():
    df[cols] = df[cols].fillna(df[cols].median())

In [11]:
df.isnull().sum()

date_id                          0
D1                               0
D2                               0
D3                               0
D4                               0
                                ..
V8                               0
V9                               0
forward_returns                  0
risk_free_rate                   0
market_forward_excess_returns    0
Length: 98, dtype: int64

In [12]:
for col in ['forward_returns', 'market_forward_excess_returns']:
    df[f'{col}_lag1'] = df[col].shift(1)
    df[f'{col}_rolling_mean5'] = df[col].rolling(window=5).mean()

In [13]:
target = 'market_forward_excess_returns'
features = sum(feature_groups.values(), []) + ['forward_returns_lag1', 'market_forward_excess_returns_rolling_mean5']
df_model = df.dropna(subset=features + [target])

In [14]:
train = df_model[df_model['date_id'] < df_model['date_id'].max() - 180]
test = df_model[df_model['date_id'] >= df_model['date_id'].max() - 180]

In [15]:
from lightgbm import LGBMRegressor

model = LGBMRegressor()
model.fit(train[features], train[target])
preds = model.predict(test[features])

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007632 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 22073
[LightGBM] [Info] Number of data points in the train set: 8805, number of used features: 96
[LightGBM] [Info] Start training from score 0.000051

In [16]:
def map_to_allocation(pred, threshold=0.0):
    return np.clip(1 + pred, 0, 2)

allocations = map_to_allocation(preds)

In [17]:
# Simulated daily portfolio returns
simulated_returns = allocations * test['forward_returns']

# Calculate cumulative return
cumulative_return = (1 + simulated_returns).cumprod()

# Estimate volatility
volatility = simulated_returns.std()

# Estimate Sharpe-like score (simplified)
excess_returns = simulated_returns - test['risk_free_rate']
sharpe_like = excess_returns.mean() / excess_returns.std()

In [18]:
simulated_returns

8809    0.012050
8810    0.005981
8811    0.011122
8812    0.000067
8813   -0.010589
          ...
8985    0.002459
8986    0.002316
8987    0.002898
8988    0.008347
8989    0.000099
Name: forward_returns, Length: 181, dtype: float64

In [19]:
cumulative_return

8809    1.012050
8810    1.018103
8811    1.029426
8812    1.029495
8813    1.018593
          ...
8985    1.098541
8986    1.101085
8987    1.104276
8988    1.113493
8989    1.113603
Name: forward_returns, Length: 181, dtype: float64

In [20]:
df_test = pd.read_csv('/kaggle/input/hull-tactical-market-prediction/test.csv')

# Apply same feature grouping
feature_groups = {
    'D': [col for col in df_test.columns if col.startswith('D')],
    'E': [col for col in df_test.columns if col.startswith('E')],
    'I': [col for col in df_test.columns if col.startswith('I')],
    'M': [col for col in df_test.columns if col.startswith('M')],
    'P': [col for col in df_test.columns if col.startswith('P')],
    'S': [col for col in df_test.columns if col.startswith('S')],
    'V': [col for col in df_test.columns if col.startswith('V')],
}

for group, cols in feature_groups.items():
    df_test[cols] = df_test[cols].fillna(df_test[cols].median())

In [21]:
df_test['lagged_forward_returns'] = df_test['lagged_forward_returns'].fillna(0)
df_test['lagged_market_forward_excess_returns'] = df_test['lagged_market_forward_excess_returns'].fillna(0)

In [22]:
features = sum(feature_groups.values(), []) + ['lagged_forward_returns', 'lagged_market_forward_excess_returns']

In [23]:
preds_test = model.predict(df_test[features])

In [24]:
def map_to_allocation(pred, threshold=0.0):
    return np.clip(1 + pred, 0, 2)

allocations_test = map_to_allocation(preds_test)

In [25]:
submission = pd.DataFrame({
    'date_id': df_test['date_id'],
    'allocation': allocations_test
})

In [26]:
submission.head()

   date_id  allocation
0     8980    1.003289
1     8981    0.981208
2     8982    0.983179
3     8983    1.007667
4     8984    1.006107

In [27]:
submission.to_csv('submission.csv',index=False)